# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.default]                                         # Define a profile name
url = "https://free-rpc.nethermind.io/sepolia-juno/v0_7" 
accounts-file = "safe_haven_account_2.json"                        
account = "safe_haven_account_2.json"                                     
keystore = "safe_haven_2.json"                                 

[sncast.first]    
url = "https://free-rpc.nethermind.io/sepolia-juno/v0_7" 
accounts-file = "safe_haven_account.json"                        
account = "safe_haven_account.json"                                     
keystore = "safe_haven.json"

[sncast.second]    
url = "https://free-rpc.nethermind.io/sepolia-juno/v0_7" 
accounts-file = "safe_haven_account_2.json"                        
account = "safe_haven_account_2.json"                                     
keystore = "safe_haven_2.json"  